name: testing
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+19

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  firebase_core: 
  firebase_storage: 
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_svg: ^1.1.3
  get: ^4.6.5
  google_fonts: ^6.1.0
  masonry_grid: ^1.0.0
  package_info: ^2.0.2
  provider: ^6.0.3
  shimmer: ^2.0.0
  unity_ads_plugin: ^0.3.8
  onepref: ^0.0.14
  restart_app: ^1.2.1
  lottie:

flutter_native_splash:
    color: "#f5f5f5"
    image: assets/sgc.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - font/
    - assets/pp.jpg
    - assets/logo-jazzdev.png
    - assets/translates/
    - assets/sgc.png
    # carousel
    - assets/carousel.jpg
    - assets/carousel1.jpg
    - assets/carousel1.1.png
    - assets/carousel1.2.jpg
    # assets makanan
    - assets/apel.jpg
    - assets/pepaya.jpg
    - assets/wortel.jpg
    - assets/madu.jpg
    - assets/uh.jpg
    - assets/jangkrik.jpg
    - assets/kecoadubia.jpg
    - assets/telurrebus.jpg

    - assets/gender.jpg
    - assets/cr.jpg
    - assets/fruits.svg
    - assets/care.svg
    - assets/cage.svg
    - assets/kangaroo.svg
    - assets/question.svg
    - assets/td.svg
    - assets/menu.svg
    - assets/info.svg
    - assets/jenis.svg
    - assets/gender.svg
    - assets/penyakit.svg
    - assets/sugar-glider.svg
    - assets/prize.png
    - assets/dark-mode.png

    # language
    - assets/language.svg
    - assets/indonesia.svg
    - assets/english.svg
    - assets/spain.svg
    - assets/france.svg
    - assets/portugal.png
    - assets/italy.png
    - assets/rusia.png
    - assets/thailand.png
    - assets/germany.png
    - assets/vietnam.png
    - assets/china.png
    - assets/removeads_lottie.json


    - assets/kandangsg.jpg
    - assets/aksesoris.jpg
    - assets/alaskandang.jpg
    - assets/kakibengkak.jpg
    - assets/hairloss.jpg
    - assets/diare.jpeg
    - assets/katarak.jpg
    - assets/panduanpotongkuku.jpg
    - assets/breeding.jpg
    - assets/mandi.jpg
    - assets/sg.jpg
    # assets jenis sg
    - assets/cg.jpg
    - assets/whiteface.jpg
    - assets/albino.jpg
    - assets/creamino.jpg
    - assets/blackbeauty.jpg
    - assets/leu.jpg
    - assets/piebal.jpg
    - assets/ringtail.jpg
    - assets/whitetip.jpg
    - assets/platinum.jpg
    - assets/mosaic.jpg
    - assets/tpm.jpg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
